### ISSUE TITLE
SNS-MQ135 working at 5V

### ISSUE THREAD

**Issue by alessandro-dallatorre** [Flowm/air-quality#2]
Hi,

Is there any issue in using a 5V gas sensor as an analog input for the Teensy?
Also the VCC pin of the sensor will be connected to 3.3V, is this correct?

Regards,
Alex

**Comment by alessandro-dallatorre** [comment]
Same issue for the SM-PWM-01C Dust Sensor, it operates at 5V.

**Comment by Flowm** [comment]
Hey,
according to the [vendor documentation](https://www.pjrc.com/teensy/teensy31.html) the used pins are 5V tolerant.

> All digital pins are 5 volt tolerant on Teensy 3.2 & 3.1. However, the analog-only pins (A10-A14), AREF, Program and Reset are 3.3V only. 

The MQ135 is connected to A0 (which is also a digital pin and thus 5V capable) so everything should be fine.
(See https://github.com/Flowm/air-quality/blob/master/air-sense/wiring/air-monitor_bb.svg and https://www.pjrc.com/teensy/pinout.html)

VCC of MQ135 (and SM-PWM-01C) is connected to Vin (5V when connecting over usb).

Greetings
Flo

**Comment by alessandro-dallatorre** [comment]
Hey,

Thank you for your kind reply.
I agree with you about the A0 connection, but shouldn't the other data connections coming from the 5V sensors and going to the analog pins be converted with a Level Converter (5V to 3.3V) in order to have a value in the adjusted (0-3.3V) range instead of a value in 0-5V where the range 3.3-5 will be considered as 3.3?

Thank you so much for your interesting project, I'm looking forward to assembling all the hardware and software!!!

Bests,
Alessandro

**Comment by Flowm** [comment]
Good question,
I haven't really looked into it much before, seems like you're right ([Vendor statement on that topic](
https://forum.pjrc.com/threads/27168-Teensy-3-1-and-quot-5V-tolerance-quot?p=98055&viewfull=1#post98055)).

So far the only way to get sensor close to the maximum readout was exposing it to lighter gas. During normal room conditions the sensor normally stays within the 0-200 range (0-20%) so 3.3V would already be really bad indoor air quality I guess :)

Still, using a level converter for the MQ135 sounds like a good idea to have the full measurement range available.

**Comment by alessandro-dallatorre** [comment]
Yes.
Thank you for your feedback!
